import { catchError } from "../../utilities/error.handler.js";

export const signup = catchError(async (req,res,next)=>{

})
export const signin = catchError(async (req,res,next)=>{
    
})

export const logout = catchError(async (req,res,next)=>{
    
})

export const forgetPassword = catchError(async (req,res,next)=>{
    
})