import { catchError } from "../../utilities/error.handler.js";

export const addCupon = catchError(async (req,res,next)=>{

})

export const getCupon = catchError(async (req,res,next)=>{

})

export const updateCupon = catchError(async (req,res,next)=>{
    
})

export const deleteCupon = catchError(async (req,res,next)=>{
    
})

export const getAllCupons = catchError(async (req,res,next)=>{

})

export const deleteAllCupons = catchError(async (req,res,next)=>{
    
})