import { catchError } from "../../utilities/error.handler.js";

export const addReview = catchError(async (req,res,next)=>{

})

export const getReview = catchError(async (req,res,next)=>{

})

export const updateReview = catchError(async (req,res,next)=>{
    
})

export const deleteReview = catchError(async (req,res,next)=>{
    
})

export const getAllReviewsOnTheProduct = catchError(async (req,res,next)=>{

})

export const deleteAllReviewsOnTheProduct = catchError(async (req,res,next)=>{

})